//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.ServicoReuters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoReuters.IServicoConsultarPreco")]
    public interface IServicoConsultarPreco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoConsultarPreco/Consultar", ReplyAction="http://tempuri.org/IServicoConsultarPreco/ConsultarResponse")]
        double Consultar(string ativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoConsultarPreco/Consultar", ReplyAction="http://tempuri.org/IServicoConsultarPreco/ConsultarResponse")]
        System.Threading.Tasks.Task<double> ConsultarAsync(string ativo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoConsultarPrecoChannel : Negocio.ServicoReuters.IServicoConsultarPreco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoConsultarPrecoClient : System.ServiceModel.ClientBase<Negocio.ServicoReuters.IServicoConsultarPreco>, Negocio.ServicoReuters.IServicoConsultarPreco {
        
        public ServicoConsultarPrecoClient() {
        }
        
        public ServicoConsultarPrecoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoConsultarPrecoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultarPrecoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultarPrecoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Consultar(string ativo) {
            return base.Channel.Consultar(ativo);
        }
        
        public System.Threading.Tasks.Task<double> ConsultarAsync(string ativo) {
            return base.Channel.ConsultarAsync(ativo);
        }
    }
}
