//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensageriaComum.DecisaoServico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Decisao", ConfigurationName="DecisaoServico.IAnalisarDados")]
    public interface IAnalisarDados {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Decisao/IAnalisarDados/Analisar")]
        void Analisar(int valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnalisarDadosChannel : MensageriaComum.DecisaoServico.IAnalisarDados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalisarDadosClient : System.ServiceModel.ClientBase<MensageriaComum.DecisaoServico.IAnalisarDados>, MensageriaComum.DecisaoServico.IAnalisarDados {
        
        public AnalisarDadosClient() {
        }
        
        public AnalisarDadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalisarDadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisarDadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisarDadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Analisar(int valor) {
            base.Channel.Analisar(valor);
        }
    }
}
